[[VMEC]]
arch = "x86_64"
git-tree-sha1 = "c473367d64bb4cf7f4bbd1cf47fb4c52c32a4019"
libgfortran_version = "4.0.0"
os = "macos"

    [[VMEC.download]]
    sha256 = "49629f9e34bf6e66a4bd253daa8f633033fc63a3b23d0648460c14a66d518bb2"
    url = "https://github.com/JuliaBinaryWrappers/VMEC_jll.jl/releases/download/VMEC-v1.0.301+0/VMEC.v1.0.301.x86_64-apple-darwin-libgfortran4.tar.gz"
[[VMEC]]
arch = "x86_64"
git-tree-sha1 = "d4fe7efc9a54949aa44a12ac19c28f11792aef98"
libgfortran_version = "5.0.0"
os = "macos"

    [[VMEC.download]]
    sha256 = "69611adaa11d09489d2eaecd88d957898d1bfe717170ac1c63b3ccb75a1add23"
    url = "https://github.com/JuliaBinaryWrappers/VMEC_jll.jl/releases/download/VMEC-v1.0.301+0/VMEC.v1.0.301.x86_64-apple-darwin-libgfortran5.tar.gz"
[[VMEC]]
arch = "x86_64"
git-tree-sha1 = "3c76f4d237e939ba747633a611cbdda669a8ea37"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[VMEC.download]]
    sha256 = "c61821910d54c270f6050f869466a8a2df727d6e468ab408fadbef79438315f4"
    url = "https://github.com/JuliaBinaryWrappers/VMEC_jll.jl/releases/download/VMEC-v1.0.301+0/VMEC.v1.0.301.x86_64-linux-gnu-libgfortran4.tar.gz"
[[VMEC]]
arch = "x86_64"
git-tree-sha1 = "34ae5f7f9570e24e376b4d16015425822ce60091"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[VMEC.download]]
    sha256 = "45fbe732e7501a2cf95d95f69cf90aba0f590cd3f9b6864eadb173e20d1be420"
    url = "https://github.com/JuliaBinaryWrappers/VMEC_jll.jl/releases/download/VMEC-v1.0.301+0/VMEC.v1.0.301.x86_64-linux-gnu-libgfortran5.tar.gz"
[[VMEC]]
arch = "x86_64"
git-tree-sha1 = "62c7a8acda555e40842ac39b26d0fc09d243235f"
libgfortran_version = "4.0.0"
os = "windows"

    [[VMEC.download]]
    sha256 = "d25ea937d642c7061559f1f4c1d827b8ed9b154f5107b484f1bab4a98a71a3c7"
    url = "https://github.com/JuliaBinaryWrappers/VMEC_jll.jl/releases/download/VMEC-v1.0.301+0/VMEC.v1.0.301.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[VMEC]]
arch = "x86_64"
git-tree-sha1 = "dfc99cc46a76355820c7163ee375cfa940b8e8b2"
libgfortran_version = "5.0.0"
os = "windows"

    [[VMEC.download]]
    sha256 = "991f99b62d83f5b8e1fa637833bdf69528450670f81d3b476617716b75ebdd64"
    url = "https://github.com/JuliaBinaryWrappers/VMEC_jll.jl/releases/download/VMEC-v1.0.301+0/VMEC.v1.0.301.x86_64-w64-mingw32-libgfortran5.tar.gz"
