# Autogenerated wrapper script for VMEC_jll for x86_64-apple-darwin-libgfortran4
export libvmec_mkl, libvmec_openblas

using MPICH_jll
using OpenBLAS_jll
using SCALAPACK_jll
using MKL_jll
using NetCDF_jll
using NetCDFF_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("VMEC")
JLLWrappers.@declare_library_product(libvmec_mkl, "@rpath/libvmec_mkl.0.dylib")
JLLWrappers.@declare_library_product(libvmec_openblas, "@rpath/libvmec_openblas.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(MPICH_jll, OpenBLAS_jll, SCALAPACK_jll, MKL_jll, NetCDF_jll, NetCDFF_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libvmec_mkl,
        "lib/libvmec_mkl.0.dylib",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libvmec_openblas,
        "lib/libvmec_openblas.0.dylib",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
