# Autogenerated wrapper script for VMEC_jll for x86_64-linux-gnu-libgfortran4-mpi+openmpi
export libvmec_mkl, libvmec_openblas

using SCALAPACK_jll
using OpenBLAS_jll
using MKL_jll
using CompilerSupportLibraries_jll
using OpenMPI_jll
using MPIPreferences
JLLWrappers.@generate_wrapper_header("VMEC")
JLLWrappers.@declare_library_product(libvmec_mkl, "libvmec_mkl.so.0")
JLLWrappers.@declare_library_product(libvmec_openblas, "libvmec_openblas.so.0")
function __init__()
    JLLWrappers.@generate_init_header(SCALAPACK_jll, OpenBLAS_jll, MKL_jll, CompilerSupportLibraries_jll, OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libvmec_mkl,
        "lib/libvmec_mkl.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libvmec_openblas,
        "lib/libvmec_openblas.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
